### ISSUE TITLE
Option for using local package version

### ISSUE THREAD

**Issue by littmus** [bndr/pipreqs#10]
When we need a compatibility for legacy codes, we cannot always uses latest version for package.
I think utilizing these information also can help to solve #5.

**Comment by bndr** [comment]
We can provide --use-local option that will look for packages in site-packages/dist-packages of python instead of making requests to pypi for latest version.

**Comment by bndr** [comment]
This was implemented in version 0.2.0

**Comment by littmus** [comment]
oops.. I forgot to comment important thing.
We can use the method from pip library, `get_installed_distributions`.
I compared with your implementation with this [code](https://gist.github.com/littmus/5aa370b1de8e9ca35c33)
```
24 ['Cython', '_jpype', '_markerlib', 'bs4', 'colorama', 'dateutil', 'jiphy', 'magic', 'matplotlib', 'numpy', 'pafy', 'pip', 'pushbullet', 'pyparsing', 'pytz', 'pywinusb', 'requests', 'seaborn', 'six', 'virtualenv', 'websocket', 'wheel', 'wikipedia', 'youtube_dl']
28 ['Cython', 'JPype1', 'Pafy', 'beautifulsoup4', 'colorama', 'cvxopt', 'hidapi2', 'jiphy', 'matplotlib', 'mps-youtube', 'numpy', 'pip', 'pushbullet.py', 'pyparsing', 'python-dateutil', 'python-magic', 'pytz', 'pyusb', 'pywinusb', 'requests', 'seaborn', 'setuptools', 'six', 'virtualenv', 'websocket-client', 'wheel', 'wikipedia', 'youtube-dl']
beautifulsoup4 (4.3.2)
colorama (0.3.3)
cvxopt (1.1.4)
Cython (0.21.2)
hidapi2 (0.7.99-5)
jiphy (1.0.0)
JPype1 (0.5.7)
matplotlib (1.4.3)
mps-youtube (0.2.3)
numpy (1.9.2)
Pafy (0.3.72)
pip (6.1.1)
pushbullet.py (0.8.1)
pyparsing (2.0.3)
python-dateutil (2.4.2)
python-magic (0.4.6)
pytz (2015.2)
pyusb (1.0.0rc1)
pywinusb (0.3.3)
requests (2.5.0)
seaborn (0.5.1)
setuptools (7.0)
six (1.9.0)
virtualenv (12.1.1)
websocket-client (0.30.0)
wheel (0.24.0)
wikipedia (1.4.0)
youtube-dl (2015.3.24)
```

**Comment by bndr** [comment]
Yes, but with the code currently in pipreqs we get the real import name from package name (e.g that bs4 means beautifulSoup4) instead of only package name

**Comment by littmus** [comment]
You're right. I think we can use both methods and make the matching table for import-package name.
