### ISSUE TITLE
Missed PyPi module for requirements

### ISSUE THREAD

**Issue by hcbomb** [bndr/pipreqs#105]
Hello!

I have pipreqs missing a critical python module I'm using and would like some clarification on how to validate what I'm seeing. In short, I've locally installed AWS _boto3_ to my mac laptop and am running pipreqs there, but am not seeing the results in the generated requirements.txt. I do not believe AWS SDK is a standard library.

OSX 10.11.6

Printing _pipreqs_ to console, ignoring PyPi referencing:
```
bin $ pwd
<path>/bin
bin $ pipreqs . --use-local --print
Babel==2.3.4
cryptography==1.7.1
certifi==2017.11.5
pymongo==3.4.0
Pygments==2.1.3
simplejson==3.11.1
INFO: Successfully output requirements
```
Printing pipreqs to console, using default PyPi referencing:
```
$ pipreqs . --print
Babel==2.3.4
cryptography==1.7.1
certifi==2017.11.5
pymongo==3.4.0
Pygments==2.1.3
simplejson==3.11.1
Image==1.5.16
pyOpenSSL==17.3.0
Pillow==4.3.0
Beaker==1.9.0
elementtree==1.2.6-20050316
protobuf==3.4.0
isodate==0.6.0
lingua==4.13
mock==2.0.0
ndg_httpsclient==0.4.3
pretty==0.1
pyasn1==0.3.7
rfc3987==1.3.7
strict_rfc3339==0.7
unittest2==1.1.0
webcolors==1.7
win_inet_pton==1.0.1
PyYAML==3.12
INFO: Successfully output requirements
```

Validating installed, targeted python module:
```
bin $ pip freeze | grep boto
boto==2.45.0
boto3==1.4.7
botocore==1.7.43
```

PyPi module validation:
```
bin $ pip search boto3 | grep -i "AWS SDK"
boto3-meiqia (1.4.5)         - The AWS SDK for Python
boto3 (1.4.7)                - The AWS SDK for Python
boto3_extensions (0.4.5)     - Extensions to the AWS SDK for Python
```

File import validation:
```
bin $ head -15 <file>.py

# encoding = utf-8

import sys
import os
import boto3
import json
import copy
import time
import csv
import re
import datetime
import traceback
import botocore.exceptions
```

I also have the folder installed locally to the folder:
```
bin $ find . -maxdepth 1 -type d
.
./boto3
./boto3-1.4.5.dist-info
./botocore
./botocore-1.5.94.dist-info
./concurrent
./dateutil
./docutils
./docutils-0.14.dist-info
./futures-3.1.1.dist-info
./jmespath
./jmespath-0.9.3.dist-info
./modinput_wrapper
./python_dateutil-2.6.1.dist-info
./s3transfer
./s3transfer-0.1.10.dist-info
./six-1.10.0.dist-info
```

I'm using pipreqs to generate a requirements file so that I don't have to push library code to my repo. Please let me know if you have any questions or any guidance on what's happening with pipreqs to ignore the _boto3_ library either locally or installed from inclusion for requirements list.

Thanks!

**Comment by jonafato** [comment]
Creating a new test file and running `pipreqs` (both the latest PyPI release and the `master` branch from GitHub) seems to work for me and produce `boto3` in the generated requirements file. Can you provide the output of the following commends to help debug?

```sh
$ pipreqs --version
$ which pipreqs
$ pip --version
```

**Comment by hcbomb** [comment]
`$ which pipreqs
pipreqs is /anaconda/bin/pipreqs
$ pip --version
pip 9.0.1 from /lib/python2.7/site-packages (python 2.7)`

Forgot that I use Anaconda python, so it may be related?

**Comment by jonafato** [comment]
The `--use-local` option searches for packages that are locally installed to the same Python environment as your `pipreqs` install. In this case, that's your Anaconda install. Your `pip` points to your macOS system Python, so if you install things using `pip install` and then try to collect those packages via `pipreqs --use-local`, your environments will differ and will likely produce incorrect results.

To solve this issue, make sure your `pip` and `pipreqs` both live in the same Python environment. The easiest approach here is to use a [virtualenv](https://virtualenv.pypa.io/en/stable/) or a [conda environment](https://conda.io/docs/user-guide/tasks/manage-environments.html).

This doesn't appear to be a `pipreqs` bug, so I'm going to close this issue. If you find that this behavior persists even when working within a single Python environment, we can reopen it.
