### ISSUE TITLE
pip install -r requirements.txt  

### ISSUE THREAD

**Issue by yuanqin27** [bndr/pipreqs#110]
‘pip install -r requirements.txt  ’ ，can i replace pip to conda?

**Comment by datatalking** [comment]
I found this in google groups.

https://groups.google.com/a/continuum.io/forum/#!topic/conda/PiM9sjWyXFU

**Comment by jonafato** [comment]
@datatalking Thanks for the link. From the conda documentation linked there, it looks like the desired command is `conda env create -f requirements.txt`.
