### ISSUE TITLE
Not compatible with Python3 new syntax.

### ISSUE THREAD

**Issue by DevRoss** [bndr/pipreqs#113]
Not compatible with syntax like this:
`def foo(param: someclass) -> someclass:`

**raise SyntaxError: invalid syntax**

**Comment by jonafato** [comment]
It sounds like you're using `pipreqs` installed into a Python 2 environment. `pipreqs` only cares about imports, and the following example works correctly for me. I'm going to close this issue, but if you can reproduce it with a minimal working example, feel free to reopen, and I'll help get things working.

----

```
(tempenv-5a99241259c7) /t/tmp> cat foo.py
import flask
import requests


def foo(param: flask.Flask) -> requests.Request:
    pass

(tempenv-5a99241259c7) /t/tmp> pipreqs . --print
requests==2.18.4
Flask==0.12.2
INFO: Successfully output requirements
```
