### ISSUE TITLE
Missing flask-mysql

### ISSUE THREAD

**Issue by robertmartin8** [bndr/pipreqs#123]
pipreqs can't seem to find `flask-mysql`. To be fair, this isn't really the fault of pipreqs because `flask-mysql` still hasn't updated their import syntax like many other flask extensions. For now, `flask-mysql` is imported via:

```python
from flaskext.mysql import MySQL
``` 
I imagine this weird syntax makes it difficult to parse, because 'flaskext.mysql' has no apparent relation to `flask-mysql`.

It is probably not worth fixing this, as flask-mysql should really be the ones to update. But just an FYI for anyone having a similar problem.

**Comment by zwq0666** [comment]
hi,do you have a facebook or msn account?

**Comment by jonafato** [comment]
This import style has been deprecated in the Flask world for some time, and support for it was removed entirely in Flask 1.0. Once `flask-mysql` and projects using it update to the standard import style, `pipreqs` should work as expected.
