### ISSUE TITLE
pipreqs not capturing all imports - recurly

### ISSUE THREAD

**Issue by smittysmee** [bndr/pipreqs#128]
I am having issues capturing Recurly lib.
pip install recurly 

Leverage it with a python file via import

https://pypi.org/project/recurly

**Comment by jonafato** [comment]
I'm unable to reproduce this with a simple Python file containing only `import recurly`. When running `pipreqs .`, I get the expected `requirements.txt` file containing `recurly==2.8.6`.

Can you provide a minimal example demonstrating this issue?

**Comment by smittysmee** [comment]
I have attempted to create the steps. Here is the python  file 
**Python Script To Test**
```
# req_test.py
from lib import recurly
print 'Recurly Test'
recurly.DEFAULT_CURRENCY = 'USD'
print 'Currency: {}'.format(recurly.DEFAULT_CURRENCY)
print 'Test Finished'
```
**SH Commands**
```
pip install -t lib recurly
touch lib/__init__.py
python req_test.py
pipreqs . --debug --print
```

**Comment by jonafato** [comment]
I'm not sure that `pipreqs` can support this particular workflow. Once a dependency is vendored, the import is coming from the local copy and is treated like any other code in your project, so `pipreqs` can't know that this is a library coming from PyPI and not one that just happens to share the same name.

**Comment by smittysmee** [comment]
Besides manually managing these packages and adding them to the requirements document, do you have any recommendations for handling this case?

**Comment by smittysmee** [comment]
Essentially, I need to maintain & keep track of packages that have been vendored and are also used by the vendored packages and build the requirements.txt as the tool is already doing. I wasn't sure if this was a feature within pipreqs :)

**Comment by jonafato** [comment]
I think I get the picture now. As stated, I'm not sure that `pipreqs` can (or should) do this. However, if your imports were `import recurly`, etc. and you added `lib/` to your `PYTHONPATH`, you'd have the option to do `pipreqs . --ignore lib`.

**Comment by smittysmee** [comment]
Great. Thank you
