### ISSUE TITLE
Invalid syntax for Python 3.5.2

### ISSUE THREAD

**Issue by tandelDipak** [bndr/pipreqs#145]
**dipak environments $** source syslog/bin/activate
**(syslog) dipak environments $** pipreqs /home/dipak/environments/
ERROR: Failed on file: /home/dipak/environments/debug.py
Traceback (most recent call last):
  File "/home/dipak/environments/syslog/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/home/dipak/environments/syslog/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 396, in main
    init(args)
  File "/home/dipak/environments/syslog/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 341, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "/home/dipak/environments/syslog/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 91, in get_all_imports
    raise exc
  File "/home/dipak/environments/syslog/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 77, in get_all_imports
    tree = ast.parse(contents)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 116
    0 0 1
      ^
SyntaxError: invalid syntax
**(syslog) dipak environments $** python --version
Python 3.5.2
**(syslog) dipak environments $** 

**OS Details**
Distributor ID: Ubuntu
Description: Ubuntu 16.04.5 LTS
Release: 16.04
Codename: xenial

**Virtual Environment**
My Virtual Environment is [venv](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-ubuntu-16-04). Link has detail about how I installed venv.

**Comment by jonafato** [comment]
Can you share your input file here (`debug.py`)? It looks like this is just a syntax error in the source. Does that Python file work elsewhere (e.g. in a Python shell or imported from another module)?

**Comment by tandelDipak** [comment]
The file is attached below. And there is no issue in the file it's running without any error. A screenshot is also attached.
[debug.py.tar.gz](https://github.com/bndr/pipreqs/files/2693376/debug.py.tar.gz)
![screenshot from 2018-12-19 11-01-47](https://user-images.githubusercontent.com/15157792/50200930-f94ed800-037d-11e9-929e-3ee75e00257c.png)

**Comment by tandelDipak** [comment]
Now it's showing some different error.
![screenshot from 2018-12-19 11-09-05](https://user-images.githubusercontent.com/15157792/50201068-a88baf00-037e-11e9-8a36-e5bffea91b72.png)

**Comment by tandelDipak** [comment]
@jonafato can you help me?

**Comment by jonafato** [comment]
@tandelDipak It looks like your project directory contains the source to [this library](https://pypi.org/project/tesseract/). Inside the `tesseract` directory there is a file called `io.py` that has Python 2-only syntax (`print` as a statement rather than a function). Because of the way `pipreqs` works, you must use a version of Python that the source code is compatible with, and Python 2-only and Python 3-only code cannot be mixed within a project. Please make sure you're running `pipreqs` only on what you intend to generate requirements for, and you should ideally install it to the same (virtual) environment that will run the program.

**Comment by tandelDipak** [comment]
@jonafato I know that my project has Python 2-only and Python 3-only code. So, if I want to remove Python 2-only code from the project how can I do that?

**Comment by jonafato** [comment]
If you're just looking to ignore the files when running `pipreqs`, there's an `--ignore` command line flag (note that this option works on directories, not individual files).

I'm going to close this issue, as there doesn't appear to be any problem with `pipreqs` here.
