### ISSUE TITLE
Option to allow using python3-pip or pip3

### ISSUE THREAD

**Issue by aalok-sathe** [bndr/pipreqs#156]
I believe the current design doesn't allow for the fact that different packages may have been installed via pip and pip3. Furthermore, different versions of packages may exist that were installed through the two modules. The program currently only looks at pip packages, not pip3.
There could be an option, as simple as --scan-pip3 to force looking at pip3 packages by default instead of pip (pip2).

**Comment by Yenthe666** [comment]
As Python 3 is becoming more mainstream it would be great to be able to do both ways around even.
