### ISSUE TITLE
Exception when 'import' is used in comments

### ISSUE THREAD

**Issue by kvdveer** [bndr/pipreqs#17]
A freshly installed pipreqs (in a venv) crashes on pylint source (in a venv in my case)

Offending line is: https://bitbucket.org/logilab/pylint/src/cc5990f6a12a467d09567bfc1b210ba999f6cb13/pylint/test/functional/unused_import.py?at=default#cl-3 

```
~/src/c3 $ pipreqs .
Traceback (most recent call last):
  File "/home/koert/src/c3/.ve2/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/home/koert/src/c3/.ve2/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 167, in main
    init(args)
  File "/home/koert/src/c3/.ve2/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 139, in init
    candidates = get_all_imports(args['<path>'])
  File "/home/koert/src/c3/.ve2/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 48, in get_all_imports
    res = map(get_name_without_alias, item.split(","))
  File "/home/koert/src/c3/.ve2/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 130, in get_name_without_alias
    name = REGEXP[0].match(name.strip()).groups(0)[0]
AttributeError: 'NoneType' object has no attribute 'groups'
~/src/c3 $ pip freeze
docopt==0.6.2
pipreqs==0.2.4
requests==2.7.0
yarg==0.1.9
```

**Comment by xsteadfastx** [comment]
same problem here. i tried installing pipreqs with pipsi. get the same error.

**Comment by bndr** [comment]
Fixed in version 0.2.5

**Comment by kvdveer** [comment]
Wow. That's some fast response time. Thank you.

**Comment by kvdveer** [comment]
While testing this fix, I just ran pipreqs over a collection of virtualenvs on my dev machine. I found these lines causing similar issues with version 0.2.5

```python
# astroid
import zipimport  # manager.py
import import_package_subpackage_module  # tests/testdata/python2/data/package/absimport.py

# IPython
from importlib.machinery import all_suffixes  # core/completerlib.py
import importlib  # html/notebookapp.py
from IPython.utils.importstring import import_item  # Many files

# Nose
from nose.importer import Importer, add_path, remove_path  # loader.py

# pyflakes 
from pyflakes.test.test_imports import Test as TestImports  # test/test_doctests.py

# setuptools
import zipimport  # command/easy_install.py

# twisted
from importlib import invalidate_caches  # python/test/test_deprecate.py
```

**Comment by bndr** [comment]
Interesting, thanks for reporting.

**Comment by bndr** [comment]
This should be fixed in the latest version, I've added your test cases https://github.com/bndr/pipreqs/blob/master/tests/_data/test.py

**Comment by kvdveer** [comment]
I can confirm all of the above issues are fixed.

I've run pipreqs on all of the virtualenvs on our CI, and I had no more crashes; so pipreqs is able to parse at least most popular (and a few less popular) codebases.

**Comment by bndr** [comment]
Thanks, if you come across any more bugs, feel free to open an Issue.

On Tue, May 12, 2015 at 8:18 am, bndr/pipreqs
<reply@reply.github.com>
wrote:
I can confirm all of the above issues are fixed.

I've run pipreqs on all of the virtualenvs on our CI, and I had no more crashes;
so pipreqs is able to parse at least most popular (and a few less popular)
codebases.

—
Reply to this email directly or view it on GitHub
[https://github.com/bndr/pipreqs/issues/17#issuecomment-101149320] .[https://github.com/notifications/beacon/ABF6cF0Vnlb9AFaU-6zL9CVulxkzljVGks5oIZLIgaJpZM4EWSGJ.gif]
