### ISSUE TITLE
Clean up requirements.txt

### ISSUE THREAD

**Issue by mknecht** [bndr/pipreqs#18]
Hey,

does pipreqs somehow support cleaning up a requirements.txt, or at least telling you which dependencies can be deleted? That would be very useful for any longer-running project. And given what `pipres` currently does, it may already do that? 

Thanks for the work!

Cheers,
murat

**Comment by bndr** [comment]
This feature is not currently implemented, but I like the suggestion, I'll see what i can do, thanks!

**Comment by cclauss** [comment]
There is a tool called `diff` that will do an effective job of this.  ;-)

**Comment by jayvdb** [comment]
re ```diff```, I have a nicely formatted requirements.txt, so merely diff'ing the generated file against the existing requirements.txt isnt helpful.

I too would like an option to see the differences against my requirements.txt listed, or amended into my requirements.txt

**Comment by jayvdb** [comment]
https://github.com/dveselov/rparse might be useful to parse the existing requirements.txt

**Comment by kxrd** [comment]
Implemented in #77

**Comment by philfreo** [comment]
This can be closed now it seems, thanks to `--clean`?
