### ISSUE TITLE
zsh: command not found: pipreqs

### ISSUE THREAD

**Issue by msjahid** [bndr/pipreqs#215]

**Comment by scv-m** [comment]
Try this https://github.com/bndr/pipreqs/issues/69#issuecomment-298758892

**Comment by unknown989** [comment]
if you're in windows ,try the following:
`set PATH=%PATH%;C:/path/to/python`
if linux:
`export PATH=/path/to/python;$PATH`

**Comment by alan-barzilay** [comment]
The issue seems to be resolved, feel free to reopen it if there is still a problem
