### ISSUE TITLE
Empty requirements.txt file

### ISSUE THREAD

**Issue by ashu-tosh-kumar** [bndr/pipreqs#221]
I am trying to create a `requirements.txt` file for my project. Using `--debug` as argument, I can see that `pyreqs` is detecting the packages but it's not writing anything to the `requirements.txt` file. It is creating an empty file.

[*pipreqs Issue Video*](https://imgur.com/a/Fxix21d)

**Comment by icedrowning** [comment]
same as @ashu-tosh-kumar 
bro, Have you ever solve the problem? 
At current dir,which has my python file,I used [pipreqs . --encoding=utf8 --force]
But the requirements.txt is empty

**Comment by icedrowning** [comment]
sorry it was my bad. python file forget to ad .py postfix. after added,it works normally

**Comment by ashu-tosh-kumar** [comment]
Hi, I didn't solve the problem. I will try adding .py as you mentioned.

**Comment by alan-barzilay** [comment]
Pipreqs currently does not attempt to open any file that is not a .py file. I will close this issue but feel free to reopen it if adding the .py extension hasn't solved the issue

**Comment by khoo-teewan** [comment]
I am trying to run Pipreqs in the powershell and under the directory where my python program (.py files) resides. I got a blank requirement.txt file.  Not sure what is the problem.  Anyone can advise..

**Comment by LAKSHAYNE** [comment]
facing the same issue , kept my file alone in the directory "creator"  and ran pipreqs 'creator' file was created but was blank!!!!!

**Comment by PARKER-X** [comment]
same issue can u send me solution for this issue

**Comment by andrii-kliuha** [comment]
I had the same issue. And I found out that pipreqs works differently than pip freeze. In order to generate Not an empty file with pipreqs command you should have some imports in your project's files, because pipreqs's looking only for modules that are directly used in a project. For instance, you've installed a bunch of libraries and in one of your .py file you have 'from selenium import webdriver' it will generate txt with selenium only.

**Comment by saisasi-choda** [comment]
im having the similar issue any inputs to solve the problem

**Comment by morisono** [comment]
I found https://github.com/harichselvamc/AutoReqGen
