### ISSUE TITLE
pipreqs does not add github3.py to the requirements file

### ISSUE THREAD

**Issue by ryan-rozario** [bndr/pipreqs#226]
When pipreqs encounters `import github3` it does not know which package we plan to import.

After installing `pip install github3.py `to get github3 in the environment, then pipreqs gives both packages.

https://pypi.org/project/github3.py/

ryan-rozario/pipreqs-action#6

**Comment by alan-barzilay** [comment]
Hi! I believe there is a mapping missing from github3 to github3.py
If you make a pr adding the following line to the [mapping](https://github.com/bndr/pipreqs/blob/master/pipreqs/mapping) file I will merge it:
`github3:github3.py`

**Comment by alan-barzilay** [comment]
Thank you for the PR! Now that it is merged this should be fixed in the next release, which I hope to release soon
