### ISSUE TITLE
Problems with pyfunctional

### ISSUE THREAD

**Issue by SwiftWinds** [bndr/pipreqs#232]
Since pyfunctional is imported with, for example, `from functional import seq`, pipreqs mistakenly adds `functional` instead of `pyfunctional` to the requirements.txt file.

**Comment by liem-dq** [comment]
It looks like `pyfunctional` isn't mapped. You can fix this by adding an entry to the [mapping](https://github.com/bndr/pipreqs/blob/060f52f59774c2fb8e24698da0a74cc7f6cfb8c9/pipreqs/mapping) file: `functional:pyfunctional`. Ideally, you should also submit a pull request with the updated file, but it seems like this project is a little inactive.

**Comment by SwiftWinds** [comment]
Hmm... I see. I submitted a PR, but assuming the worst, are there any good workarounds? Like alternative, more active forks? What other methods would you suggest to share a dependency list among a team? Poetry? Resorting to just virtualenv + `pip freeze`? Writing the requirements.txt file manually?

I tried Conda, but it was slow and had outdated packages. Also, exporting without the path to the Anaconda installation and platform-dependent packages is still [an open issue](https://github.com/conda/conda/issues/4339), and having to use the Anaconda terminal on Windows was a hassle.

**Comment by liem-dq** [comment]
What we did was fork the repository, and make the desired changes ourselves. Our CI pushes an updated requirements.txt file automatically using `pipreqs` whenever a commit is made, so all we we had to do was make sure our version was installed on the CI server instance by first cloning our fork and then installing it locally. We already had a pipeline set up, so it was relatively trivial to add and you can probably do it fairly easily with Github Actions. Obviously, this is just what worked for us and there might be a better approach out there.

**Comment by SwiftWinds** [comment]
I see. Thanks, I'll probably do something like this. Too bad specifying project dependencies in Python is just so much worse than languages like Node.js or Go.

**Comment by alan-barzilay** [comment]
Hello! @liem-dq is right and the package is a little inactive, but I intend to change this in the coming weeks. I just became a maintainer and I'm going through all issues and PRs, I'm probably going to start by the mapping issues that are pretty straightforward (thank you @SwiftWinds  for the PR!).

@liem-dq if there any changes you made to pipreqs in your fork that you believe may benefit the rest of the community, please consider making a pull request. I would be happy to review and merge them!

**Comment by SwiftWinds** [comment]
This is awesome news. Thank you so much, @alan-barzilay!
