### ISSUE TITLE
Mode argument does not work?

### ISSUE THREAD

**Issue by komodovaran** [bndr/pipreqs#246]
```
>pipreqs --mode compat
Usage:
    pipreqs [options] [<path>]

>pipreqs --mode=compat
Usage:
    pipreqs [options] [<path>]
```

**Comment by SergeiDBykov** [comment]
I have the same issue. How to run the script with this option correctly?

**Comment by alan-barzilay** [comment]
hi! how did you install pipreqs? this should only be available through cloning the repo since we haven't made a new release with it yet.
Did you install it through pip as normal?

**Comment by SergeiDBykov** [comment]
@alan-barzilay Hi. I don't quit remember, probably with pip, but definitely not cloning repo.
Thanks.

**Comment by alan-barzilay** [comment]
I will be closing this issue since this feature is not available on the current release of pipqreqs, but feel free to reopen it if you cloned the repository in the right branch and the problem persisted
