### ISSUE TITLE
Check if requirements.txt exist before proceeding further inspection

### ISSUE THREAD

**Issue by pkesavap** [bndr/pipreqs#285]
Feel free to close this issue, if already implemented.
I ran pipreqs ./  to generate requirements.txt without knowing i already had one, and after about 4 minutes, pipreqs  shows the warning 
```
WARNING: requirements.txt already exists, use --force to overwrite it
```
Maybe we could do that check first before proceeding with other introspection? 

Thanks

**Comment by pkesavap** [comment]
Version:
 pipreqs --version
0.4.11

**Comment by jsethlui** [comment]
Hi! I know it's been awhile since `pipreqs` has last been updated, but I was hoping to tackle this issue? I'm mostly looking to get some experience into open-source development

**Comment by clvnkhr** [comment]
Hi, I'm new to this but [the fix](https://github.com/bndr/pipreqs/pull/344) was simple so I went ahead and opened a pull request. Tox passed locally but I think I need someone else in order to proceed.
