### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 3608: illegal multibyte sequence

### ISSUE THREAD

**Issue by code4happylife** [bndr/pipreqs#326]
After I run   
```

pipreqs . 
```
I got errors like below:

File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\pipreqs\pipreqs.py", line 115, in get_all_imports
    contents = f.read()

UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 3608: illegal multibyte sequence

**Comment by ConyKitty** [comment]
Try to add the parameter `--encoding` with UTF-8:

`pipreqs . --encoding UTF-8`

**Comment by alan-barzilay** [comment]
fixed in #414
