### ISSUE TITLE
pipreqs still missing some imports

### ISSUE THREAD

**Issue by audiofeature** [bndr/pipreqs#34]
I have another project where I use

from sklearn import preprocessing
#from sklearn import cross_validation
from sklearn.cross_validation import StratifiedShuffleSplit

However, pipreqs does not include scikit-learn in the requirements file.

**Comment by audiofeature** [comment]
It also misses:

import h5py
from progressbar import ProgressBar, ETA # installed via pip install progressbar2

**Comment by dizballanze** [comment]
It also misses:

```python
from picklefield.fields import PickledObjectField  # pip install django-picklefield
```

**Comment by bndr** [comment]
Just tested the new version. picklefield, h5py, Progressbar and scikit-learn are identified correctly. If you find any more packages, please report them.

**Comment by eric-roquemore-sp** [comment]
import MySQLdb

**Comment by kr1zz** [comment]
``` python
import gc
import sys
import time
from datetime import datetime, timedelta
from osgeo import gdal, osr
import numpy as np
import wasdi
```

however, the `requirements.txt` generated with `pipreqs` only include `numpy`, `GDAL` and `wasdi`

I am using version 0.4.10
