### ISSUE TITLE
Dynamic module dependencies

### ISSUE THREAD

**Issue by nrhine1** [bndr/pipreqs#40]
Perhaps this is an edge case, but I found that because I have an IPython build in an unignored subdirectory of my package, I am getting a weird dependency output. (specifically, 
A == 1.0
B == 1.0.0
)

The culprit file: test_deepreload.py: https://github.com/ipython/ipython/blob/40c34d3369c3d271149e13ac07f1bd2f5a716635/IPython/lib/tests/test_deepreload.py)
Relevant snippet included:

`with open(os.path.join(tmpdir, 'A.py'), 'w') as f:
                f.write("class Object(object):\n    pass\n")
            with open(os.path.join(tmpdir, 'B.py'), 'w') as f:
                f.write("import A\n")
            import A
            import B`

This is less pipreqs fault and more IPythons fault, but it's an annoying edge case nonetheless

**Comment by bndr** [comment]
Well that's an interesting edge case. Thanks for reporting

**Comment by jonafato** [comment]
Interestingly, [a](https://pypi.python.org/pypi/a) and [b](https://pypi.python.org/pypi/b) exist as valid package names on PyPI. I'm not sure that `pipreqs` is behaving badly here. What would be the desired alternative behavior?
