### ISSUE TITLE
Missed psycopg2

### ISSUE THREAD

**Issue by tkjone** [bndr/pipreqs#42]
Here is my pip freeze (including `pipreqs`)

```
Django==1.9.2
django-environ==0.4.0
docopt==0.6.2
pipreqs==0.4.2
psycopg2==2.6.1
requests==2.9.1
six==1.10.0
wheel==0.29.0
yarg==0.1.9
```

Here is the generated requirements.txt

```
Django == 1.9.2
django_environ == 0.4.0
environ == 1.0
```

Seems to have added an `environ` package and not included `psycopg2`.  

As a separate note, if I uninstall `pipreqs` it does not remove the other dependency packages that it installed on it's own. Perhaps a different method of dependency management?

**Comment by akaihola** [comment]
@tkjone, Python's package management doesn't support removing transitive dependencies. This is not dependent on how `pipreqs` was packaged, but will happen with any Python package you try to remove.

**Comment by jonafato** [comment]
`pipreqs` can only detect packages that you import. If you use `psycopg2` via Django's ORM but don't directly import it, there's no way `pipreqs` can know about it.
