### ISSUE TITLE
Spacing inconsistency between example and actual output

### ISSUE THREAD

**Issue by dellsystem** [bndr/pipreqs#47]
First of all, this is really useful tool, and thanks for writing it!

In the README, the example output looks like

```
wheel==0.23.0
Yarg==0.1.9
docopt==0.6.2
```

whereas the actual output would be

```
wheel == 0.23.0
Yarg == 0.1.9
docopt == 0.6.2
```

(with spaces around the ==). Are the extra spaces intentional? Should the README be updated? All of my existing requirements.txt files use the format without spaces, so it would be great if there was a way to omit the spaces.

**Comment by bndr** [comment]
There's no particular reason why there are spaces there. The Readme must have been written before the spaces have been added. I'll make the necessary changed and release a new version without the spaces.

**Comment by dellsystem** [comment]
Awesome, thanks!

**Comment by bndr** [comment]
Should be fixed in the new release.
