### ISSUE TITLE
zope issue

### ISSUE THREAD

**Issue by k1-hedayati** [bndr/pipreqs#48]
It seems pipreqs can't find correct package name for zope

**Comment by jonafato** [comment]
@k1-hedayati Can you provide a minimal example demonstrating the issue?

**Comment by k1-hedayati** [comment]
Sorry this issue is for long time ago, I don't exactly remember what happend and why I created issue

**Comment by jonafato** [comment]
Closing this issue for now. If it can be reproduced, feel free to reopen.
