### ISSUE TITLE
Install packages from github

### ISSUE THREAD

**Issue by ritviksahajpal** [bndr/pipreqs#49]
I pip install a package directly from github (it's instructions state so):
https://github.com/perrygeo/jenks

when I run pipreqs on the resulting project, the resulting requirements.txt file has a line
`jenks.egg==info`

Shouldn't it be:
`-e git+https://github.com/perrygeo/jenks.git@197130a220b5b2e1b8cbc3d1ad70211e6441030f#egg=jenks`

**Comment by bndr** [comment]
No, it is not currently possible to identify packages that are not installed using the PyPi repository.
