### ISSUE TITLE
Difference between package name and import name makes problem

### ISSUE THREAD

**Issue by littmus** [bndr/pipreqs#5]
For example, to import `beautifulsoup4` package, it should be `import bs4`.
So pipreqs cannot find the `beautifulsoup4` package from pypi server.
I don't have an idea to resolve this problem... :(

**Comment by cclauss** [comment]
Code that I used [`elsewhere`](https://github.com/cclauss/pythonista-module-versions/blob/master/pythonista_module_versions.py) to solve the same problem:

```python
# Translate from Python module --> PyPI module name
pypi_dict = { 'bs4' : 'beautifulsoup4',
                    'dateutil' : 'py-dateutil',
                    'faker' : 'Faker',
                    'yaml' : 'PyYAML',
                    'Crypto' : 'pycrypto' }
# [ ... ]
module_name = pypi_dict.get(module_name, module_name)

**Comment by littmus** [comment]
Upper or lower case is not a problem.
Who should define the dictionary? If user, it's somewhere annoying job... I think I would just manually input to `requirements.txt` than do that.

**Comment by cclauss** [comment]
I am advocating that this lookup table dict goes somewhere in the application code.  This information should remain mostly the same for the vast majority of users.

**Comment by bndr** [comment]
This is quite an annoying problem. 

Theoretically we can make our own lookup table with "packageName" -> "importName" but then we'd need to go over each package in PyPi and find those that have different package names.

**Comment by cclauss** [comment]
This is annoying but not a showstopper.  This is open source... "given enough eyeballs, all bugs are shallow".

We can start the project off with a "good enough" lookup dictionary and over time users will send in pull requests to add entries to continue to fill in any gaps.  Most projects will not hit this issue in the first place and as the lookup table continues to get improved, there will be fewer and fewer lookup misses.

**Comment by bndr** [comment]
I agree, but still "good enough" should be big enough that it covers most of the cases.

**Comment by littmus** [comment]
There is also another problem making such dict.
In case of [`django-haystack`](https://pypi.python.org/pypi/django-haystack) and [`haystack`](https://pypi.python.org/pypi/haystack), both use `import haystack`.
What should we do in such case?

**Comment by cclauss** [comment]
Are there other imports that indicate that this is a django project?  If so, the special case logic should not be too difficult.  Let's hope there are not lots of haystack-like modules.

**Comment by bndr** [comment]
Should be fixed in latest version 0.2.2

**Comment by paolobenve** [comment]
please reopen it: https://github.com/Isotr0py/pillow-jpegxl-plugin/issues/99

**Comment by cclauss** [comment]
Do PEP723 headers help?

Does `uv run --with=` help or similar settings in pipx?
