### ISSUE TITLE
Creating Requirements txt for GAE Directory setup

### ISSUE THREAD

**Issue by Shub1427** [bndr/pipreqs#50]
Hi,
I have tried various [options] in the pipreqs command, but haven't yet properly able to create a requirements.txt file, if the Libraries for the project are placed in some local directory, instead of Python Package directory.

For example, while working on Google Appengine projects, it's necessary to put all required third-party libraries in a local folder inside project root, and then change the Python env during runtime.

I wanted to create requirements.txt for such kind of project environments.
Is it possible using pipreqs?

**Comment by jonafato** [comment]
`pipreqs` and `requirements.txt` are usually used to describe dependencies to install. If you're vendoring all of your dependencies (as required by GAE), what added value do `pipreqs` and a requirements file add? Is this for documentation purposes (e.g. to let other developers know what requirements are vendored without needing to look through a dependencies directory)?

**Comment by larsblumberg** [comment]
GAE uses `requirements.txt` to install all dependencies that are required by the project. Hence the OP wants to use `pipreqs` to create `requirements.txt`.

**Comment by jonafato** [comment]
Got it, I misunderstood the question at first.

@Shub1427 I don't know of any reason `pipreqs` wouldn't work for this use case. If you have an example that it fails for, I'm happy to help debug.

**Comment by jonafato** [comment]
I'm going to close this issue for now. If `pipreqs` can be demonstrated to fail to work with GAE, please reopen it.
