### ISSUE TITLE
Jupyter Notebooks support

### ISSUE THREAD

**Issue by philippschw** [bndr/pipreqs#51]
I just tried using pipreqs, but it seems useless for my workflow heavily relying on Jupyter notebooks. 

Will Jupyter notebooks be supported in the future?

**Comment by bndr** [comment]
I'm sorry but, Jupyter will not be supported any time soon, I will leave this Issue open for future reference, if someday I find time to look into this.

**Comment by nise** [comment]
Any updates here? I would love to use it.

**Comment by DanielHabenicht** [comment]
Seems to be possible, someone wrote a wrapper: https://github.com/ivanlen/pipreqsnb

**Comment by alan-barzilay** [comment]
implemented in #414
