### ISSUE TITLE
pipreqs missing imports

### ISSUE THREAD

**Issue by tpd001** [bndr/pipreqs#59]
Hi, thanks for working on this.
pipreqs 0.4.6 appears to miss some imports, including but not limited to the following:

(ve) [tdonahue@timdev backend]$pipreqs --print .
easysnmp==0.2.4
portal==0.3.1
psycopg2==2.6.2
pymodbus==1.2.0
pyodbc==3.1.1
pytz==2016.10
redis==2.10.5
urllib3==1.19.1
INFO: Successfully output requirements

(ve) [tdonahue@timdev backend]$!find
find . -type f -name "*.py" | xargs grep futures
./modbus_collector.py:from concurrent.futures import as_completed
./meter_collector.py:from concurrent.futures import as_completed
./rest_collector.py:from concurrent.futures import as_completed
./vfd_collector.py:from concurrent.futures import as_completed
./collection_main.py:from concurrent.futures import ThreadPoolExecutor

(ve) [tdonahue@timdev backend]$pipreqs --version
0.4.6

(ve) [tdonahue@timdev backend]$python --version
Python 2.7.9

I understand concurrent.futures is a back-ported Python3 feature.  If pipreqs is Python version-aware that might be good to know.  The overall goal is to split requirements files, which 'pip freeze' doesn't seem to support.

Thanks for any help.

**Comment by bndr** [comment]
concurrent.futures is part of the standard library, so it shouldn't be in a requirements.txt. Pipreqs only fetches those libraries that are external and need explicit installation.

**Comment by tpd001** [comment]
Thanks for the fast reply.  Let me see if I can find another example (before you close the issue :)).

**Comment by tpd001** [comment]
OK, there are other examples of the problem, but I'll retract my assertion that this is a pipreqs issue.  There is more likely some issue of our environment, bc. unless I install futures (at least) the interpreter raises a "No module named" exception at runtime.

Thanks again for your help, if I again think there may be an issue or have a nontrivial question I'll write.

**Comment by bndr** [comment]
Sure thing, if you find any problems let me know. Closing this issue for now.

**Comment by dhitals** [comment]
This is not an issue with `pipreqs` but a request/improvement.

I use HDF5 with pandas. While pytables (`tables`) is never explicitly invoked/imported, it is a requirement. For that reason, it never shows up in `requirements.txt` and my code ends up breaking at the server level. Another example would be 'seaborn' and `matplotlib` although I have not explicitly tested for that.

I am not sure how to test for such dependencies, but there has to be a way, right? Thanks.
