### ISSUE TITLE
--ignore does not work for more than one folder

### ISSUE THREAD

**Issue by simonm3** [bndr/pipreqs#63]
e.g. fails if you do this

     pipreqs . --ignore dist build

**Comment by bndr** [comment]
It's comma separated.

**Comment by simonm3** [comment]
Thanks. Not sure if there is a standard but I use setup.py and docopt. In
both of these repeated options are space separated.

**Comment by simonm3** [comment]
Ah. My mistake. Multiple option args are not possible so commas is the only way.
