### ISSUE TITLE
flake8 configuration

### ISSUE THREAD

**Issue by james-prior** [bndr/pipreqs#64]
Please include your flake8 configuration file in the repo and update CONTRIBUTING.rst to use it.

Before making any changes, I followed the instructions in CONTRIBUTING.rst, and flake8 complained much. I used:

Centos 7(.2)
Python 2.7.5
virtualenvwrapper 4.7.2
virtualenv 15.1.0
pip 9.0.1
flake8 3.3.0

flake8 output:

(pipreqs) [doj@pan pipreqs]$ flake8 pipreqs tests
pipreqs/pipreqs.py:11:80: E501 line too long (108 > 79 characters)
pipreqs/pipreqs.py:19:80: E501 line too long (80 > 79 characters)
pipreqs/pipreqs.py:69:80: E501 line too long (87 > 79 characters)
pipreqs/pipreqs.py:82:80: E501 line too long (90 > 79 characters)
pipreqs/pipreqs.py:85:80: E501 line too long (91 > 79 characters)
pipreqs/pipreqs.py:90:5: E303 too many blank lines (3)
pipreqs/pipreqs.py:92:80: E501 line too long (96 > 79 characters)
pipreqs/pipreqs.py:94:80: E501 line too long (84 > 79 characters)
pipreqs/pipreqs.py:118:80: E501 line too long (99 > 79 characters)
pipreqs/pipreqs.py:121:1: E302 expected 2 blank lines, found 1
pipreqs/pipreqs.py:127:80: E501 line too long (86 > 79 characters)
pipreqs/pipreqs.py:128:30: E127 continuation line over-indented for visual indent
pipreqs/pipreqs.py:130:1: E302 expected 2 blank lines, found 1
pipreqs/pipreqs.py:130:80: E501 line too long (87 > 79 characters)
pipreqs/pipreqs.py:135:80: E501 line too long (91 > 79 characters)
pipreqs/pipreqs.py:159:80: E501 line too long (90 > 79 characters)
pipreqs/pipreqs.py:223:49: W291 trailing whitespace
pipreqs/pipreqs.py:225:51: E251 unexpected spaces around keyword / parameter equals
pipreqs/pipreqs.py:225:53: E251 unexpected spaces around keyword / parameter equals
pipreqs/pipreqs.py:253:80: E501 line too long (103 > 79 characters)
tests/test_pipreqs.py:23:80: E501 line too long (113 > 79 characters)
tests/test_pipreqs.py:23:112: E202 whitespace before ']'
tests/test_pipreqs.py:27:80: E501 line too long (87 > 79 characters)
tests/test_pipreqs.py:28:80: E501 line too long (100 > 79 characters)
tests/test_pipreqs.py:29:80: E501 line too long (108 > 79 characters)
tests/test_pipreqs.py:57:80: E501 line too long (85 > 79 characters)
tests/test_pipreqs.py:65:80: E501 line too long (110 > 79 characters)
tests/test_pipreqs.py:74:80: E501 line too long (97 > 79 characters)
tests/test_pipreqs.py:88:80: E501 line too long (83 > 79 characters)
tests/test_pipreqs.py:89:70: E231 missing whitespace after ':'
tests/test_pipreqs.py:89:80: E501 line too long (98 > 79 characters)
tests/test_pipreqs.py:89:92: E231 missing whitespace after ':'
tests/test_pipreqs.py:98:80: E501 line too long (83 > 79 characters)
tests/test_pipreqs.py:100:80: E501 line too long (83 > 79 characters)
tests/test_pipreqs.py:101:70: E231 missing whitespace after ':'
tests/test_pipreqs.py:101:80: E501 line too long (98 > 79 characters)
tests/test_pipreqs.py:101:92: E231 missing whitespace after ':'
tests/test_pipreqs.py:114:80: E501 line too long (127 > 79 characters)
tests/test_pipreqs.py:114:80: E231 missing whitespace after ':'
tests/test_pipreqs.py:114:102: E231 missing whitespace after ':'
tests/test_pipreqs.py:125:80: E501 line too long (85 > 79 characters)
tests/test_pipreqs.py:130:70: E231 missing whitespace after ':'
tests/test_pipreqs.py:130:80: E501 line too long (116 > 79 characters)
tests/test_pipreqs.py:130:92: E231 missing whitespace after ':'
tests/test_pipreqs.py:139:80: E501 line too long (87 > 79 characters)
tests/test_pipreqs.py:152:80: E501 line too long (137 > 79 characters)
tests/test_pipreqs.py:153:80: E501 line too long (113 > 79 characters)
tests/test_pipreqs.py:160:80: E501 line too long (96 > 79 characters)
tests/test_pipreqs.py:161:23: E127 continuation line over-indented for visual indent
tests/test_pipreqs.py:162:32: E231 missing whitespace after ':'
tests/test_pipreqs.py:163:38: E231 missing whitespace after ':'
tests/test_pipreqs.py:164:33: E231 missing whitespace after ':'
tests/test_pipreqs.py:165:13: E124 closing bracket does not match visual indentation
tests/test_pipreqs.py:167:80: E501 line too long (98 > 79 characters)
tests/test_pipreqs.py:173:5: E303 too many blank lines (2)
tests/_invalid_data/invalid.py:1:17: E401 multiple imports on one line
tests/_invalid_data/invalid.py:1:24: E999 SyntaxError: invalid syntax
tests/_data/test.py:2:80: E501 line too long (117 > 79 characters)
tests/_data/test.py:4:1: F401 'xml.sax' imported but unused
tests/_data/test.py:5:1: F401 'os.path as test' imported but unused
tests/_data/test.py:6:1: F401 'sys.argv as test2' imported but unused
tests/_data/test.py:7:1: F401 'sys.flags' imported but unused
tests/_data/test.py:9:1: F401 'collections.OrderedDict' imported but unused
tests/_data/test.py:9:1: F401 'collections.deque' imported but unused
tests/_data/test.py:9:1: F401 'collections.Counter' imported but unused
tests/_data/test.py:11:1: F401 'requests' imported but unused
tests/_data/test.py:17:1: F401 'importlib.invalidate_caches' imported but unused
tests/_data/test.py:20:1: F811 redefinition of unused 'zipimport' from line 14
tests/_data/test.py:20:1: F401 'zipimport' imported but unused
tests/_data/test.py:22:1: F401 'importlib.machinery.all_suffixes' imported but unused
tests/_data/test.py:23:1: F401 'importlib' imported but unused
tests/_data/test.py:25:1: F401 'IPython.utils.importstring.import_item' imported but unused
tests/_data/test.py:29:1: F401 'pyflakes.test.test_imports.Test as TestImports' imported but unused
tests/_data/test.py:32:1: F401 'nose.importer.add_path' imported but unused
tests/_data/test.py:32:1: F401 'nose.importer.Importer' imported but unused
tests/_data/test.py:32:1: F401 'nose.importer.remove_path' imported but unused
tests/_data/test.py:34:1: F401 'atexit' imported but unused
tests/_data/test.py:35:1: F404 from __future__ imports must occur at the beginning of the file
tests/_data/test.py:36:1: F401 'docopt.docopt' imported but unused
tests/_data/test.py:37:1: F401 'curses' imported but unused
tests/_data/test.py:37:14: E401 multiple imports on one line
tests/_data/test.py:38:1: F811 redefinition of unused 'logging' from line 37
tests/_data/test.py:38:1: F401 'logging' imported but unused
tests/_data/test.py:39:1: F401 'os' imported but unused
tests/_data/test.py:40:1: F811 redefinition of unused 'sqlite3' from line 37
tests/_data/test.py:40:1: F401 'sqlite3' imported but unused
tests/_data/test.py:41:1: F401 'time' imported but unused
tests/_data/test.py:42:1: F401 'sys' imported but unused
tests/_data/test.py:43:1: F401 'signal' imported but unused
tests/_data/test.py:44:1: F401 'bs4' imported but unused
tests/_data/test.py:45:1: F401 'nonexistendmodule' imported but unused
tests/_data/test.py:46:1: F401 'boto as b' imported but unused
tests/_data/test.py:46:1: F401 'peewee as p' imported but unused
tests/_data/test.py:46:17: E401 multiple imports on one line
tests/_data/test.py:48:1: F401 'flask.ext.somext' imported but unused
tests/_data/test.py:49:1: F401 'sqlalchemy.model' imported but unused
tests/_data/test.py:53:5: F401 'json' imported but unused
tests/_data/test.py:55:1: F401 'models' imported but unused
tests/_data/test.py:61:1: E305 expected 2 blank lines after class or function definition, found 1
tests/_data/test.py:61:1: E402 module level import not at top of file
tests/_data/test.py:61:1: F401 'after_method_is_valid_even_if_not_pep8' imported but unused
tests/_data_duplicated_deps/db.py:1:1: F401 'pymongo' imported but unused
tests/_data_duplicated_deps/db.py:2:1: F401 'bson.objectid.ObjectId' imported but unused
tests/_data_ignore/test.py:2:80: E501 line too long (117 > 79 characters)
tests/_data_ignore/test.py:4:1: F401 'xml.sax' imported but unused
tests/_data_ignore/test.py:5:1: F401 'os.path as test' imported but unused
tests/_data_ignore/test.py:6:1: F401 'sys.argv as test2' imported but unused
tests/_data_ignore/test.py:7:1: F401 'sys.flags' imported but unused
tests/_data_ignore/test.py:9:1: F401 'collections.OrderedDict' imported but unused
tests/_data_ignore/test.py:9:1: F401 'collections.deque' imported but unused
tests/_data_ignore/test.py:9:1: F401 'collections.Counter' imported but unused
tests/_data_ignore/test.py:11:1: F401 'requests' imported but unused
tests/_data_ignore/test.py:17:1: F401 'importlib.invalidate_caches' imported but unused
tests/_data_ignore/test.py:20:1: F811 redefinition of unused 'zipimport' from line 14
tests/_data_ignore/test.py:20:1: F401 'zipimport' imported but unused
tests/_data_ignore/test.py:22:1: F401 'importlib.machinery.all_suffixes' imported but unused
tests/_data_ignore/test.py:23:1: F401 'importlib' imported but unused
tests/_data_ignore/test.py:25:1: F401 'IPython.utils.importstring.import_item' imported but unused
tests/_data_ignore/test.py:29:1: F401 'pyflakes.test.test_imports.Test as TestImports' imported but unused
tests/_data_ignore/test.py:32:1: F401 'nose.importer.add_path' imported but unused
tests/_data_ignore/test.py:32:1: F401 'nose.importer.Importer' imported but unused
tests/_data_ignore/test.py:32:1: F401 'nose.importer.remove_path' imported but unused
tests/_data_ignore/test.py:34:1: F401 'atexit' imported but unused
tests/_data_ignore/test.py:35:1: F404 from __future__ imports must occur at the beginning of the file
tests/_data_ignore/test.py:36:1: F401 'docopt.docopt' imported but unused
tests/_data_ignore/test.py:37:1: F401 'curses' imported but unused
tests/_data_ignore/test.py:37:14: E401 multiple imports on one line
tests/_data_ignore/test.py:38:1: F811 redefinition of unused 'logging' from line 37
tests/_data_ignore/test.py:38:1: F401 'logging' imported but unused
tests/_data_ignore/test.py:39:1: F401 'os' imported but unused
tests/_data_ignore/test.py:40:1: F811 redefinition of unused 'sqlite3' from line 37
tests/_data_ignore/test.py:40:1: F401 'sqlite3' imported but unused
tests/_data_ignore/test.py:41:1: F401 'time' imported but unused
tests/_data_ignore/test.py:42:1: F401 'sys' imported but unused
tests/_data_ignore/test.py:43:1: F401 'signal' imported but unused
tests/_data_ignore/test.py:44:1: F401 'bs4' imported but unused
tests/_data_ignore/test.py:45:1: F401 'nonexistendmodule' imported but unused
tests/_data_ignore/test.py:46:1: F401 'boto as b' imported but unused
tests/_data_ignore/test.py:46:1: F401 'peewee as p' imported but unused
tests/_data_ignore/test.py:46:17: E401 multiple imports on one line
tests/_data_ignore/test.py:48:1: F401 'flask.ext.somext' imported but unused
tests/_data_ignore/test.py:49:1: F401 'sqlalchemy.model' imported but unused
tests/_data_ignore/test.py:53:5: F401 'json' imported but unused
tests/_data_ignore/test.py:55:1: F401 'models' imported but unused
tests/_data_ignore/test.py:61:1: E305 expected 2 blank lines after class or function definition, found 1
tests/_data_ignore/test.py:61:1: E402 module level import not at top of file
tests/_data_ignore/test.py:61:1: F401 'after_method_is_valid_even_if_not_pep8' imported but unused
tests/_data_ignore/.ignore_second/ignored.py:2:1: F401 'pattern.web.plaintext' imported but unused
tests/_data_ignore/.ignore_second/ignored.py:2:1: F401 'pattern.web.Twitter' imported but unused
tests/_data_ignore/.ignore_second/ignored.py:2:43: W292 no newline at end of file
tests/_data_ignore/.ignored_dir/ignored.py:2:1: F401 'click' imported but unused
tests/_data_ignore/.ignored_dir/ignored.py:2:13: W292 no newline at end of file
(pipreqs) [doj@pan pipreqs]$ python setup.py test
running test
running egg_info
writing requirements to pipreqs.egg-info/requires.txt
writing pipreqs.egg-info/PKG-INFO
writing top-level names to pipreqs.egg-info/top_level.txt
writing dependency_links to pipreqs.egg-info/dependency_links.txt
writing entry points to pipreqs.egg-info/entry_points.txt
reading manifest file 'pipreqs.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no files found matching 'stdlib' under directory 'docs'
warning: no files found matching 'mapping' under directory 'docs'
writing manifest file 'pipreqs.egg-info/SOURCES.txt'
running build_ext
test_custom_pypi_server (tests.test_pipreqs.TestPipreqs) ... ok
test_deduplicate_dependencies (tests.test_pipreqs.TestPipreqs) ... ok
test_get_all_imports (tests.test_pipreqs.TestPipreqs) ... ok
test_get_import_name_without_alias (tests.test_pipreqs.TestPipreqs) ... ok
test_get_imports_info (tests.test_pipreqs.TestPipreqs) ... ok
test_get_use_local_only (tests.test_pipreqs.TestPipreqs) ... ok
test_ignored_directory (tests.test_pipreqs.TestPipreqs) ... ok
test_init (tests.test_pipreqs.TestPipreqs) ... ok
test_init_local_only (tests.test_pipreqs.TestPipreqs) ... ok
test_init_overwrite (tests.test_pipreqs.TestPipreqs) ... WARNING:root:Requirements.txt already exists, use --force to overwrite it
ok
test_init_savepath (tests.test_pipreqs.TestPipreqs) ... ok
test_invalid_python (tests.test_pipreqs.TestPipreqs) ... ERROR:root:Failed on file: /home/doj/pipreqs/tests/_invalid_data/invalid.py
ok

----------------------------------------------------------------------
Ran 12 tests in 15.563s

OK
(pipreqs) [doj@pan pipreqs]$ pip freeze
appdirs==1.4.3
configparser==3.5.0
docopt==0.6.2
enum34==1.1.6
flake8==3.3.0
mccabe==0.6.1
packaging==16.8
-e git+https://github.com/bndr/pipreqs.git@714393fcea65fa91cc593d8967ddd408bb5ad9e8#egg=pipreqs
pluggy==0.4.0
py==1.4.32
pycodestyle==2.3.1
pyflakes==1.5.0
pyparsing==2.2.0
requests==2.13.0
six==1.10.0
tox==2.6.0
virtualenv==15.1.0
yarg==0.1.9
(pipreqs) [doj@pan pipreqs]$

**Comment by bndr** [comment]
autopep8 Is used to conform to the styling standards. Contributing page needs updated, closing this issue, will update the contributing guide
