### ISSUE TITLE
-bash: pipreqs: command not found

### ISSUE THREAD

**Issue by varadig** [bndr/pipreqs#69]
When I try to run the pipreqs from cli, I got ther is no command found.
I miss something? The installation process and the usage is jus this:

```
$ pip install pipreqs
$ pipreqs [path/to/project]
```

**Comment by kkaiser** [comment]
I have the same issue, when installing it with `--user`

**Comment by bndr** [comment]
Check that your python packages path is in your $PATH

**Comment by varadig** [comment]
## Here is the echo of the PATH variable:

Varadis-iMac:~ varadig$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/local/bin:/opt/local/sbin:/usr/bin/c++:/usr/bin/make:/Volumes/Work/Android/android-sdk/platform-tools/:/Volumes/Work/Android/ndk:/Volumes/Work/Android/sdk/platform-tools:/Volumes/Work/Android/sdk/tools:**/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/**

## The site-packages path:

Varadis-iMac:pipreqs varadig$ **cd /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/**
Varadis-iMac:site-packages varadig$ ls
Beaker-1.8.1-py2.7.egg-info
Cython
Cython-0.25.2-py2.7.egg-info
Mako-1.0.6-py2.7.egg-info
MarkupSafe-0.23-py2.7.egg-info
PyYAML-3.12-py2.7.egg-info
README
appdirs-1.4.3-py2.7.egg-info
appdirs.py
appdirs.pyc
backports
backports.ssl_match_hostname-3.5.0.1-py2.7.egg-info
beaker
beautifulsoup4-4.5.3.dist-info
bs4
cairo
certifi
certifi-2017.04.17-py2.7.egg-info
colorama
colorama-0.3.9.dist-info
concurrent
core
cython.py
cython.pyc
dateutil
docopt-0.6.2-py2.7.egg-info
docopt.py
docopt.pyc
drv_libxml2.py
drv_libxml2.pyc
easy-install.pth
easy_install.py
easy_install.pyc
funcsigs
funcsigs-1.0.2.dist-info
futures-3.1.1.dist-info
gevent
gevent-1.2.1.dist-info
gi
glib
gobject
gotocorepy-0.0.1a0-py2.7.egg-info
greenlet-0.4.12-py2.7.egg-info
greenlet.so
gst-0.10
gstoption.so
gtk-2.0
libproxy.py
libxml2.py
libxml2.pyc
libxml2_python-2.9.4-py2.7.egg-info
libxml2mod.so
livestreamer
livestreamer-1.12.2-py2.7.egg-info
livestreamer_cli
mako
markupsafe
matplotlib
matplotlib-1.4.3-py2.7-nspkg.pth
matplotlib-1.4.3.dist-info
mock
mock-2.0.0.dist-info
mpl_toolkits
nose
nose-1.3.7-py2.7.egg-info
numpy
numpy-1.12.1-py2.7.egg-info
packaging
packaging-16.8-py2.7.egg-info
pbr
pbr-3.0.0.dist-info
pigar
pigar-0.6.10.dist-info
pip
pip-9.0.1-py2.7.egg-info
**pipreqs**
pipreqs-0.4.7.dist-info
pkg_resources
psutil
psutil-5.2.2-py2.7.egg-info
pycairo-1.10.0-py2.7.egg-info
pygobject-3.22.0-py2.7-macosx-10.11-x86_64.egg-info
pygst.pth
pygst.py
pygtk.pth
pygtk.py
pygtk.pyc
pygtk.pyo
pygtkcompat
pylab.py
pylab.pyc
pyparsing-2.2.0-py2.7.egg-info
pyparsing.py
pyparsing.pyc
python_dateutil-2.6.0.dist-info
pytz
pytz-2017.2.dist-info
pyximport
requests
requests-2.13.0.dist-info
setuptools
setuptools-35.0.1.dist-info
simplejson
simplejson-3.10.0-py2.7.egg-info
singledispatch-3.4.0.3.dist-info
singledispatch.py
singledispatch.pyc
singledispatch_helpers.py
singledispatch_helpers.pyc
six-1.10.0-py2.7.egg-info
six.py
six.pyc
tests
websocket
websocket_client-0.40.0-py2.7.egg-info
yaml
yarg
yarg-0.1.9.dist-info
youtube_dl
youtube_dl-2017.4.26.dist-info

**Comment by jonafato** [comment]
@varadig I see that you have `/Library/Frameworks/Python.framework/Versions/3.6/bin` in your `$PATH`, but you don't have the Python 2.7 version of that directory there. The `pipreqs` in that `site-packages` directory is the library, not the console script. If you add `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin` to your `$PATH`, does it work?

**Comment by varadig** [comment]
Sorry for the late reply. I added the python2.7 path to the $PATH variable, and it's working.

Thanks

**Comment by markhu** [comment]
Wait, which path exactly did you add? I'm still stuck on this error: Is this the same or different problem?

```
MacBook-Pro ~  $ pipreqs
Traceback (most recent call last):
  File "/Users/mhudson/bin/pipreqs", line 7, in <module>
    from pipreqs.pipreqs import main
ModuleNotFoundError: No module named 'pipreqs'
```

**Comment by Destaq** [comment]
I still have this issue. I can import pipreqs in the Python REPL, but I am unable to have it run as a command in zsh.

**Comment by msjahid** [comment]
zsh: command not found: pipreqs

**Comment by labuladong** [comment]
I can't find `pipreqs` command in my bin path... Anyway, I use this command to resolve this problem in python3:

```shell
python3 -m  pipreqs.pipreqs [path/to/project]
```

**Comment by sonvirgo** [comment]
> I can't find `pipreqs` command in my bin path... Anyway, I use this command to resolve this problem in python3:
> 
> ```shell
> python3 -m  pipreqs.pipreqs [path/to/project]
> ```

Work!

**Comment by dval** [comment]
On windows it's installed as `pipreq` not `pipreqs`.  That's why it can't be found with correct path settings.

**Comment by abuibaid** [comment]
> ```shell
> python3 -m  pipreqs.pipreqs [path/to/project]
> ```

it worked this way indeed, thank @labuladong

**Comment by sandyram19** [comment]
> > I can't find `pipreqs` command in my bin path... Anyway, I use this command to resolve this problem in python3:
> > ```shell
> > python3 -m  pipreqs.pipreqs [path/to/project]
> > ```
> 
> Work!

python -m pipreqs.pipreqs . 
worked for me thanks!
