### ISSUE TITLE
--clean removes some actually used packages

### ISSUE THREAD

**Issue by philfreo** [bndr/pipreqs#88]
I'm giving `pipreqs --clean requirements.txt .` a shot in my project.

It seems to do mostly a good job, but I've noticed at least one incorrect removal so far: it removed `analytics-python==1.2.6`. However [this package](https://github.com/segmentio/analytics-python) actually is used in my codebase like so:

```py
import analytics
analytics.track(...)
```

**Comment by philfreo** [comment]
Another one: `email-validator==1.0.1` got removed even though codebase says `from email_validator import validate_email`

https://pypi.python.org/pypi/email_validator/1.0.1

**Comment by philfreo** [comment]
With Flask extensions, there are lots of examples (seemingly caused by `_` vs `-` in the naming vs usage).

For example, `Flask-SeaSurf` was removed even though codebase has `from flask_seasurf import SeaSurf`.

**Comment by philfreo** [comment]
Another one: `gunicorn` was removed even though codebase says: `from gunicorn.workers.ggevent import GeventWorker`

**Comment by jonafato** [comment]
This may be due to the rules for package names as defined by [PEP 426](https://www.python.org/dev/peps/pep-0426/):
>All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.
A PR that fixes this issue via better name comparison will be merged if submitted.

**Comment by cdz620** [comment]
When I run "pipreqs --clean requirements.txt ./" twice, I had found that requirements is empty. "--clean" doesn't work well. Hope to solve this problem soon.
